services:
    app.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments: [ AppBundle\Entity\User ]

    app.repository.page:
        class: AppBundle\Repository\PageRepository
        factory: [ "@doctrine_mongodb.odm.default_document_manager", getRepository ]
        arguments: [ AppBundle\Document\Page ]
